{{- if and .Values.worker.enabled .Values.worker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wbtemporal.worker.serviceAccountName" . }}
  labels:
    {{- include "wbtemporal.worker.labels" . | nindent 4 }}
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
