{{- if and .Values.starter.enabled .Values.starter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wbtemporal.starter.serviceAccountName" . }}
  labels:
    {{- include "wbtemporal.starter.labels" . | nindent 4 }}
  {{- with .Values.starter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
